Algoritmo "entrada_e_sainda_de_dados"

// Descrição   : Entrada e saída de dados.
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 16/04/2020
Var
// Seção de Declarações das variáveis 
      nome : caractere
      nota : inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
      escreval("digite o nome do aluno")
      leia(nome)
      escreva("digite a nota de ",nome,":")
      leia(nota)
      escreva("a nota do ",nome, " é ", nota)

Fimalgoritmo